ci, update android workflow

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -19,11 +19,27 @@ workflows:
       - name: Get Flutter packages
         script: |
           flutter packages pub get
-      - name: Build AAB with Flutter
+      - name: Authenticate Google Play
+        script: |
+          echo "$GCLOUD_SERVICE_ACCOUNT_CREDENTIALS" > $HOME/google_play.json
+          gcloud auth activate-service-account --key-file=$HOME/google_play.json
+          gcloud --quiet config set project YOUR_PROJECT_ID
+      - name: Fetch and Increment Build Number
         script: |
           LATEST_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK")
+          if [ -z "$LATEST_BUILD_NUMBER" ]; then
+            echo "Failed to fetch the latest build number."
+            exit 1
+          fi
+          echo "Latest build number: $LATEST_BUILD_NUMBER"
           BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
-          echo BUILD_NUMBER       
+          if [ -z "$BUILD_NUMBER" ]; then
+            echo "Failed to increment the build number."
+            exit 1
+          fi
+          echo "New build number: $BUILD_NUMBER"
+      - name: Build AAB with Flutter
+        script: |
           flutter build appbundle --release \
             --build-name=1.0.$BUILD_NUMBER \
             --build-number=$BUILD_NUMBER
